// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProjectProtocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Utills.proto {

  /// <summary>Holder for reflection information generated from ProjectProtocol_v3.proto</summary>
  public static partial class ProjectProtocolV3Reflection {

    #region Descriptor
    /// <summary>File descriptor for ProjectProtocol_v3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProjectProtocolV3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQcm9qZWN0UHJvdG9jb2xfdjMucHJvdG8SCm1vZDEudXRpbHMiNwoHQW5n",
            "YWphdBIKCgJpZBgBIAEoBRIQCgh1c2VybmFtZRgCIAEoCRIOCgZwYXJvbGEY",
            "AyABKAkihwEKBU1lY2lMEgoKAmlkGAEgASgFEgwKBG51bWUYAiABKAkSEQoJ",
            "cHJldEJpbGV0GAMgASgBEhIKCmNhcGFjaXRhdGUYBCABKAUSIAoEZGF0YRgF",
            "IAEoCzISLm1vZDEudXRpbHMuTXlEYXRlEhsKE25yTG9jdXJpRGlzcG9uaWJp",
            "bGUYBiABKAUiaQoETWVjaRIKCgJpZBgBIAEoBRIMCgRudW1lGAIgASgJEhEK",
            "CXByZXRCaWxldBgDIAEoARISCgpjYXBhY2l0YXRlGAQgASgFEiAKBGRhdGEY",
            "BSABKAsyEi5tb2QxLnV0aWxzLk15RGF0ZSJZCgVCaWxldBIKCgJpZBgBIAEo",
            "BRIeCgRtZWNpGAIgASgLMhAubW9kMS51dGlscy5NZWNpEhIKCm51bWVDbGll",
            "bnQYAyABKAkSEAoIbnJMb2N1cmkYBCABKAUisgIKB1JlcXVlc3QSJgoEdHlw",
            "ZRgBIAEoDjIYLm1vZDEudXRpbHMuUmVxdWVzdC5UeXBlEiYKB2FuZ2FqYXQY",
            "AiABKAsyEy5tb2QxLnV0aWxzLkFuZ2FqYXRIABITCglpZEFuZ2FqYXQYAyAB",
            "KAVIABIgCgRtZWNpGAQgASgLMhAubW9kMS51dGlscy5NZWNpSAASIgoFYmls",
            "ZXQYBSABKAsyES5tb2QxLnV0aWxzLkJpbGV0SAAicQoEVHlwZRIJCgVMT0dJ",
            "ThAAEgoKBkxPR09VVBABEg8KC0dFVF9NRUNJVVJJEAISFgoSR0VUX01FQ0lV",
            "UklfTElCRVJFEAMSEQoNQ1VNUEFSQV9CSUxFVBAEEhYKEkxPQ1VSSV9ESVNQ",
            "T05JQklMRRAFQgkKB3BheWxvYWQigwIKCFJlc3BvbnNlEicKBHR5cGUYASAB",
            "KA4yGS5tb2QxLnV0aWxzLlJlc3BvbnNlLlR5cGUSIgoHbWVjaXVyaRgCIAMo",
            "CzIRLm1vZDEudXRpbHMuTWVjaUwSEQoJaWRBbmdhamF0GAMgASgFEiAKBWJp",
            "bGV0GAQgASgLMhEubW9kMS51dGlscy5CaWxldBIPCgdtZXNzYWdlGAUgASgJ",
            "EhsKE25yTG9jdXJpRGlzcG9uaWJpbGUYBiABKAUiRwoEVHlwZRIGCgJPSxAA",
            "EgkKBUVSUk9SEAESFAoQTkVXX01FQ0lVUklfTElTVBACEhYKEkxPQ1VSSV9E",
            "SVNQT05JQklMRRADIjIKBk15RGF0ZRIMCgR5ZWFyGAEgASgFEg0KBW1vbnRo",
            "GAIgASgFEgsKA2RheRgDIAEoBUIwChFvcmcuZXhhbXBsZS5wcm90b0IMUHJv",
            "amVjdFByb3RvqgIMVXRpbGxzLnByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Utills.proto.Angajat), global::Utills.proto.Angajat.Parser, new[]{ "Id", "Username", "Parola" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Utills.proto.MeciL), global::Utills.proto.MeciL.Parser, new[]{ "Id", "Nume", "PretBilet", "Capacitate", "Data", "NrLocuriDisponibile" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Utills.proto.Meci), global::Utills.proto.Meci.Parser, new[]{ "Id", "Nume", "PretBilet", "Capacitate", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Utills.proto.Bilet), global::Utills.proto.Bilet.Parser, new[]{ "Id", "Meci", "NumeClient", "NrLocuri" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Utills.proto.Request), global::Utills.proto.Request.Parser, new[]{ "Type", "Angajat", "IdAngajat", "Meci", "Bilet" }, new[]{ "Payload" }, new[]{ typeof(global::Utills.proto.Request.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Utills.proto.Response), global::Utills.proto.Response.Parser, new[]{ "Type", "Meciuri", "IdAngajat", "Bilet", "Message", "NrLocuriDisponibile" }, null, new[]{ typeof(global::Utills.proto.Response.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Utills.proto.MyDate), global::Utills.proto.MyDate.Parser, new[]{ "Year", "Month", "Day" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Angajat : pb::IMessage<Angajat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Angajat> _parser = new pb::MessageParser<Angajat>(() => new Angajat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Angajat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Utills.proto.ProjectProtocolV3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat(Angajat other) : this() {
      id_ = other.id_;
      username_ = other.username_;
      parola_ = other.parola_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat Clone() {
      return new Angajat(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "parola" field.</summary>
    public const int ParolaFieldNumber = 3;
    private string parola_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Parola {
      get { return parola_; }
      set {
        parola_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Angajat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Angajat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Username != other.Username) return false;
      if (Parola != other.Parola) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Parola.Length != 0) hash ^= Parola.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Parola.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Parola);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Parola.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parola);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Angajat other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Parola.Length != 0) {
        Parola = other.Parola;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Parola = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MeciL : pb::IMessage<MeciL>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MeciL> _parser = new pb::MessageParser<MeciL>(() => new MeciL());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MeciL> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Utills.proto.ProjectProtocolV3Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeciL() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeciL(MeciL other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      pretBilet_ = other.pretBilet_;
      capacitate_ = other.capacitate_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      nrLocuriDisponibile_ = other.nrLocuriDisponibile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeciL Clone() {
      return new MeciL(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pretBilet" field.</summary>
    public const int PretBiletFieldNumber = 3;
    private double pretBilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double PretBilet {
      get { return pretBilet_; }
      set {
        pretBilet_ = value;
      }
    }

    /// <summary>Field number for the "capacitate" field.</summary>
    public const int CapacitateFieldNumber = 4;
    private int capacitate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Capacitate {
      get { return capacitate_; }
      set {
        capacitate_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private global::Utills.proto.MyDate data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.MyDate Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    /// <summary>Field number for the "nrLocuriDisponibile" field.</summary>
    public const int NrLocuriDisponibileFieldNumber = 6;
    private int nrLocuriDisponibile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuriDisponibile {
      get { return nrLocuriDisponibile_; }
      set {
        nrLocuriDisponibile_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MeciL);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MeciL other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PretBilet, other.PretBilet)) return false;
      if (Capacitate != other.Capacitate) return false;
      if (!object.Equals(Data, other.Data)) return false;
      if (NrLocuriDisponibile != other.NrLocuriDisponibile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (PretBilet != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PretBilet);
      if (Capacitate != 0) hash ^= Capacitate.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (NrLocuriDisponibile != 0) hash ^= NrLocuriDisponibile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (PretBilet != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(PretBilet);
      }
      if (Capacitate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Capacitate);
      }
      if (data_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Data);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (PretBilet != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(PretBilet);
      }
      if (Capacitate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Capacitate);
      }
      if (data_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Data);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (PretBilet != 0D) {
        size += 1 + 8;
      }
      if (Capacitate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Capacitate);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (NrLocuriDisponibile != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuriDisponibile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MeciL other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.PretBilet != 0D) {
        PretBilet = other.PretBilet;
      }
      if (other.Capacitate != 0) {
        Capacitate = other.Capacitate;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Utills.proto.MyDate();
        }
        Data.MergeFrom(other.Data);
      }
      if (other.NrLocuriDisponibile != 0) {
        NrLocuriDisponibile = other.NrLocuriDisponibile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 25: {
            PretBilet = input.ReadDouble();
            break;
          }
          case 32: {
            Capacitate = input.ReadInt32();
            break;
          }
          case 42: {
            if (data_ == null) {
              Data = new global::Utills.proto.MyDate();
            }
            input.ReadMessage(Data);
            break;
          }
          case 48: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 25: {
            PretBilet = input.ReadDouble();
            break;
          }
          case 32: {
            Capacitate = input.ReadInt32();
            break;
          }
          case 42: {
            if (data_ == null) {
              Data = new global::Utills.proto.MyDate();
            }
            input.ReadMessage(Data);
            break;
          }
          case 48: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Meci : pb::IMessage<Meci>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Meci> _parser = new pb::MessageParser<Meci>(() => new Meci());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Meci> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Utills.proto.ProjectProtocolV3Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Meci() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Meci(Meci other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      pretBilet_ = other.pretBilet_;
      capacitate_ = other.capacitate_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Meci Clone() {
      return new Meci(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pretBilet" field.</summary>
    public const int PretBiletFieldNumber = 3;
    private double pretBilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double PretBilet {
      get { return pretBilet_; }
      set {
        pretBilet_ = value;
      }
    }

    /// <summary>Field number for the "capacitate" field.</summary>
    public const int CapacitateFieldNumber = 4;
    private int capacitate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Capacitate {
      get { return capacitate_; }
      set {
        capacitate_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private global::Utills.proto.MyDate data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.MyDate Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Meci);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Meci other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PretBilet, other.PretBilet)) return false;
      if (Capacitate != other.Capacitate) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (PretBilet != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PretBilet);
      if (Capacitate != 0) hash ^= Capacitate.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (PretBilet != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(PretBilet);
      }
      if (Capacitate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Capacitate);
      }
      if (data_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (PretBilet != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(PretBilet);
      }
      if (Capacitate != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Capacitate);
      }
      if (data_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (PretBilet != 0D) {
        size += 1 + 8;
      }
      if (Capacitate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Capacitate);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Meci other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.PretBilet != 0D) {
        PretBilet = other.PretBilet;
      }
      if (other.Capacitate != 0) {
        Capacitate = other.Capacitate;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Utills.proto.MyDate();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 25: {
            PretBilet = input.ReadDouble();
            break;
          }
          case 32: {
            Capacitate = input.ReadInt32();
            break;
          }
          case 42: {
            if (data_ == null) {
              Data = new global::Utills.proto.MyDate();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 25: {
            PretBilet = input.ReadDouble();
            break;
          }
          case 32: {
            Capacitate = input.ReadInt32();
            break;
          }
          case 42: {
            if (data_ == null) {
              Data = new global::Utills.proto.MyDate();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Bilet : pb::IMessage<Bilet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Utills.proto.ProjectProtocolV3Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet(Bilet other) : this() {
      id_ = other.id_;
      meci_ = other.meci_ != null ? other.meci_.Clone() : null;
      numeClient_ = other.numeClient_;
      nrLocuri_ = other.nrLocuri_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet Clone() {
      return new Bilet(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "meci" field.</summary>
    public const int MeciFieldNumber = 2;
    private global::Utills.proto.Meci meci_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.Meci Meci {
      get { return meci_; }
      set {
        meci_ = value;
      }
    }

    /// <summary>Field number for the "numeClient" field.</summary>
    public const int NumeClientFieldNumber = 3;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuri" field.</summary>
    public const int NrLocuriFieldNumber = 4;
    private int nrLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuri {
      get { return nrLocuri_; }
      set {
        nrLocuri_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Bilet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Bilet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Meci, other.Meci)) return false;
      if (NumeClient != other.NumeClient) return false;
      if (NrLocuri != other.NrLocuri) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (meci_ != null) hash ^= Meci.GetHashCode();
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (NrLocuri != 0) hash ^= NrLocuri.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (meci_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Meci);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeClient);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (meci_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Meci);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeClient);
      }
      if (NrLocuri != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NrLocuri);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (meci_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Meci);
      }
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (NrLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuri);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Bilet other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.meci_ != null) {
        if (meci_ == null) {
          Meci = new global::Utills.proto.Meci();
        }
        Meci.MergeFrom(other.Meci);
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.NrLocuri != 0) {
        NrLocuri = other.NrLocuri;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            if (meci_ == null) {
              Meci = new global::Utills.proto.Meci();
            }
            input.ReadMessage(Meci);
            break;
          }
          case 26: {
            NumeClient = input.ReadString();
            break;
          }
          case 32: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            if (meci_ == null) {
              Meci = new global::Utills.proto.Meci();
            }
            input.ReadMessage(Meci);
            break;
          }
          case 26: {
            NumeClient = input.ReadString();
            break;
          }
          case 32: {
            NrLocuri = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Utills.proto.ProjectProtocolV3Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Angajat:
          Angajat = other.Angajat.Clone();
          break;
        case PayloadOneofCase.IdAngajat:
          IdAngajat = other.IdAngajat;
          break;
        case PayloadOneofCase.Meci:
          Meci = other.Meci.Clone();
          break;
        case PayloadOneofCase.Bilet:
          Bilet = other.Bilet.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Utills.proto.Request.Types.Type type_ = global::Utills.proto.Request.Types.Type.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.Request.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.Angajat Angajat {
      get { return payloadCase_ == PayloadOneofCase.Angajat ? (global::Utills.proto.Angajat) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Angajat;
      }
    }

    /// <summary>Field number for the "idAngajat" field.</summary>
    public const int IdAngajatFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdAngajat {
      get { return HasIdAngajat ? (int) payload_ : 0; }
      set {
        payload_ = value;
        payloadCase_ = PayloadOneofCase.IdAngajat;
      }
    }
    /// <summary>Gets whether the "idAngajat" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIdAngajat {
      get { return payloadCase_ == PayloadOneofCase.IdAngajat; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "idAngajat" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIdAngajat() {
      if (HasIdAngajat) {
        ClearPayload();
      }
    }

    /// <summary>Field number for the "meci" field.</summary>
    public const int MeciFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.Meci Meci {
      get { return payloadCase_ == PayloadOneofCase.Meci ? (global::Utills.proto.Meci) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Meci;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.Bilet Bilet {
      get { return payloadCase_ == PayloadOneofCase.Bilet ? (global::Utills.proto.Bilet) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Bilet;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Angajat = 2,
      IdAngajat = 3,
      Meci = 4,
      Bilet = 5,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (IdAngajat != other.IdAngajat) return false;
      if (!object.Equals(Meci, other.Meci)) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Utills.proto.Request.Types.Type.Login) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Angajat) hash ^= Angajat.GetHashCode();
      if (HasIdAngajat) hash ^= IdAngajat.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Meci) hash ^= Meci.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Bilet) hash ^= Bilet.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Utills.proto.Request.Types.Type.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (HasIdAngajat) {
        output.WriteRawTag(24);
        output.WriteInt32(IdAngajat);
      }
      if (payloadCase_ == PayloadOneofCase.Meci) {
        output.WriteRawTag(34);
        output.WriteMessage(Meci);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        output.WriteRawTag(42);
        output.WriteMessage(Bilet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Utills.proto.Request.Types.Type.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (HasIdAngajat) {
        output.WriteRawTag(24);
        output.WriteInt32(IdAngajat);
      }
      if (payloadCase_ == PayloadOneofCase.Meci) {
        output.WriteRawTag(34);
        output.WriteMessage(Meci);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        output.WriteRawTag(42);
        output.WriteMessage(Bilet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Utills.proto.Request.Types.Type.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (HasIdAngajat) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdAngajat);
      }
      if (payloadCase_ == PayloadOneofCase.Meci) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Meci);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Utills.proto.Request.Types.Type.Login) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Angajat:
          if (Angajat == null) {
            Angajat = new global::Utills.proto.Angajat();
          }
          Angajat.MergeFrom(other.Angajat);
          break;
        case PayloadOneofCase.IdAngajat:
          IdAngajat = other.IdAngajat;
          break;
        case PayloadOneofCase.Meci:
          if (Meci == null) {
            Meci = new global::Utills.proto.Meci();
          }
          Meci.MergeFrom(other.Meci);
          break;
        case PayloadOneofCase.Bilet:
          if (Bilet == null) {
            Bilet = new global::Utills.proto.Bilet();
          }
          Bilet.MergeFrom(other.Bilet);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Utills.proto.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Utills.proto.Angajat subBuilder = new global::Utills.proto.Angajat();
            if (payloadCase_ == PayloadOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 24: {
            IdAngajat = input.ReadInt32();
            break;
          }
          case 34: {
            global::Utills.proto.Meci subBuilder = new global::Utills.proto.Meci();
            if (payloadCase_ == PayloadOneofCase.Meci) {
              subBuilder.MergeFrom(Meci);
            }
            input.ReadMessage(subBuilder);
            Meci = subBuilder;
            break;
          }
          case 42: {
            global::Utills.proto.Bilet subBuilder = new global::Utills.proto.Bilet();
            if (payloadCase_ == PayloadOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Utills.proto.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Utills.proto.Angajat subBuilder = new global::Utills.proto.Angajat();
            if (payloadCase_ == PayloadOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 24: {
            IdAngajat = input.ReadInt32();
            break;
          }
          case 34: {
            global::Utills.proto.Meci subBuilder = new global::Utills.proto.Meci();
            if (payloadCase_ == PayloadOneofCase.Meci) {
              subBuilder.MergeFrom(Meci);
            }
            input.ReadMessage(subBuilder);
            Meci = subBuilder;
            break;
          }
          case 42: {
            global::Utills.proto.Bilet subBuilder = new global::Utills.proto.Bilet();
            if (payloadCase_ == PayloadOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("LOGOUT")] Logout = 1,
        [pbr::OriginalName("GET_MECIURI")] GetMeciuri = 2,
        [pbr::OriginalName("GET_MECIURI_LIBERE")] GetMeciuriLibere = 3,
        [pbr::OriginalName("CUMPARA_BILET")] CumparaBilet = 4,
        [pbr::OriginalName("LOCURI_DISPONIBILE")] LocuriDisponibile = 5,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Utills.proto.ProjectProtocolV3Reflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      meciuri_ = other.meciuri_.Clone();
      idAngajat_ = other.idAngajat_;
      bilet_ = other.bilet_ != null ? other.bilet_.Clone() : null;
      message_ = other.message_;
      nrLocuriDisponibile_ = other.nrLocuriDisponibile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Utills.proto.Response.Types.Type type_ = global::Utills.proto.Response.Types.Type.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.Response.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "meciuri" field.</summary>
    public const int MeciuriFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Utills.proto.MeciL> _repeated_meciuri_codec
        = pb::FieldCodec.ForMessage(18, global::Utills.proto.MeciL.Parser);
    private readonly pbc::RepeatedField<global::Utills.proto.MeciL> meciuri_ = new pbc::RepeatedField<global::Utills.proto.MeciL>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Utills.proto.MeciL> Meciuri {
      get { return meciuri_; }
    }

    /// <summary>Field number for the "idAngajat" field.</summary>
    public const int IdAngajatFieldNumber = 3;
    private int idAngajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IdAngajat {
      get { return idAngajat_; }
      set {
        idAngajat_ = value;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 4;
    private global::Utills.proto.Bilet bilet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Utills.proto.Bilet Bilet {
      get { return bilet_; }
      set {
        bilet_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 5;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuriDisponibile" field.</summary>
    public const int NrLocuriDisponibileFieldNumber = 6;
    private int nrLocuriDisponibile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuriDisponibile {
      get { return nrLocuriDisponibile_; }
      set {
        nrLocuriDisponibile_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!meciuri_.Equals(other.meciuri_)) return false;
      if (IdAngajat != other.IdAngajat) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (Message != other.Message) return false;
      if (NrLocuriDisponibile != other.NrLocuriDisponibile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Utills.proto.Response.Types.Type.Ok) hash ^= Type.GetHashCode();
      hash ^= meciuri_.GetHashCode();
      if (IdAngajat != 0) hash ^= IdAngajat.GetHashCode();
      if (bilet_ != null) hash ^= Bilet.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (NrLocuriDisponibile != 0) hash ^= NrLocuriDisponibile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Utills.proto.Response.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      meciuri_.WriteTo(output, _repeated_meciuri_codec);
      if (IdAngajat != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IdAngajat);
      }
      if (bilet_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Message);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Utills.proto.Response.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      meciuri_.WriteTo(ref output, _repeated_meciuri_codec);
      if (IdAngajat != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IdAngajat);
      }
      if (bilet_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Message);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Utills.proto.Response.Types.Type.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += meciuri_.CalculateSize(_repeated_meciuri_codec);
      if (IdAngajat != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdAngajat);
      }
      if (bilet_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (NrLocuriDisponibile != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuriDisponibile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Utills.proto.Response.Types.Type.Ok) {
        Type = other.Type;
      }
      meciuri_.Add(other.meciuri_);
      if (other.IdAngajat != 0) {
        IdAngajat = other.IdAngajat;
      }
      if (other.bilet_ != null) {
        if (bilet_ == null) {
          Bilet = new global::Utills.proto.Bilet();
        }
        Bilet.MergeFrom(other.Bilet);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.NrLocuriDisponibile != 0) {
        NrLocuriDisponibile = other.NrLocuriDisponibile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Utills.proto.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            meciuri_.AddEntriesFrom(input, _repeated_meciuri_codec);
            break;
          }
          case 24: {
            IdAngajat = input.ReadInt32();
            break;
          }
          case 34: {
            if (bilet_ == null) {
              Bilet = new global::Utills.proto.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 42: {
            Message = input.ReadString();
            break;
          }
          case 48: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Utills.proto.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            meciuri_.AddEntriesFrom(ref input, _repeated_meciuri_codec);
            break;
          }
          case 24: {
            IdAngajat = input.ReadInt32();
            break;
          }
          case 34: {
            if (bilet_ == null) {
              Bilet = new global::Utills.proto.Bilet();
            }
            input.ReadMessage(Bilet);
            break;
          }
          case 42: {
            Message = input.ReadString();
            break;
          }
          case 48: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("NEW_MECIURI_LIST")] NewMeciuriList = 2,
        [pbr::OriginalName("LOCURI_DISPONIBILE")] LocuriDisponibile = 3,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MyDate : pb::IMessage<MyDate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MyDate> _parser = new pb::MessageParser<MyDate>(() => new MyDate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MyDate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Utills.proto.ProjectProtocolV3Reflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyDate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyDate(MyDate other) : this() {
      year_ = other.year_;
      month_ = other.month_;
      day_ = other.day_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MyDate Clone() {
      return new MyDate(this);
    }

    /// <summary>Field number for the "year" field.</summary>
    public const int YearFieldNumber = 1;
    private int year_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Year {
      get { return year_; }
      set {
        year_ = value;
      }
    }

    /// <summary>Field number for the "month" field.</summary>
    public const int MonthFieldNumber = 2;
    private int month_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Month {
      get { return month_; }
      set {
        month_ = value;
      }
    }

    /// <summary>Field number for the "day" field.</summary>
    public const int DayFieldNumber = 3;
    private int day_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Day {
      get { return day_; }
      set {
        day_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MyDate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MyDate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Year != other.Year) return false;
      if (Month != other.Month) return false;
      if (Day != other.Day) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Year != 0) hash ^= Year.GetHashCode();
      if (Month != 0) hash ^= Month.GetHashCode();
      if (Day != 0) hash ^= Day.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Year != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Year);
      }
      if (Month != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Month);
      }
      if (Day != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Day);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Year != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Year);
      }
      if (Month != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Month);
      }
      if (Day != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Day);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Year != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Year);
      }
      if (Month != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Month);
      }
      if (Day != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Day);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MyDate other) {
      if (other == null) {
        return;
      }
      if (other.Year != 0) {
        Year = other.Year;
      }
      if (other.Month != 0) {
        Month = other.Month;
      }
      if (other.Day != 0) {
        Day = other.Day;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Year = input.ReadInt32();
            break;
          }
          case 16: {
            Month = input.ReadInt32();
            break;
          }
          case 24: {
            Day = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Year = input.ReadInt32();
            break;
          }
          case 16: {
            Month = input.ReadInt32();
            break;
          }
          case 24: {
            Day = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
